modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Meldexun/BetterDiving/issues"
[[mods]]
modId="better_diving"
version="1.3.5"
displayName="Better Diving"
credits="Thank you Xemnes for providing the oxygen gui and seamoth gui textures."
authors="Meldexun"
description='''
TODO: fix seamoth gui, outcrop features
TODO: new sfx; seamoth modules?; docking block?
'''
